//  Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:projectid: intellij
:page-layout: guide-multipane
:page-duration: 30 minutes
:page-releasedate: 2020-01-23
:page-essential: true
:page-essential-order: 1
:page-description: Learn how to create a REST service with Open Liberty with IntelliJ.
:page-seo-title: Using IntelliJ to develop a microservice
:page-seo-description: A tutorial on how to use IntelliJ IDE to develop a microservice with Open Liberty
:guide-author: Open Liberty
:page-tags: ['MicroProfile', 'Java EE', 'Jakarta EE', 'Maven']
:page-related-guides: ['rest-client-java', 'rest-client-angularjs', 'rest-intro']
:page-permalink: /guides/{projectid}
:repo-description: Go to the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
= Using IntelliJ to develop a microservice

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to use the IntelliJ IDE to develop a microservice with Open Liberty.

== What you'll learn

IntelliJ is an integrated development environment written in Java for developing computer software.

You'll learn how to get started with IntelliJ by building and testing a simple REST service.
This service will display the JVM's system properties. The REST service will respond to `GET` requests made to the
`\http://localhost:9080/LibertyProject/System/properties` URL.

This guide is similar to https://openliberty.io/guides/rest-intro.html#creating-the-jax-rs-resource[Creating a RESTful
 web service].

== Additional prerequisite

- *IntelliJ:* For installation instructions of IntelliJ, refer to the official https://www.jetbrains.com/idea/download/[IntelliJ download documentation^].

== Getting started

The fastest way to work through this guide is to clone the Git repository and use the projects that are provided inside:

[role='command']
```
https://github.com/OpenLiberty/guide-intellij.git

cd guide-intellij
```

Make a note of the directory path that the project is being cloned to.

Start IntelliJ, select `Import Project`. On the `Import Project` dialog box, choose `Import
project from external model` and navigate to the directory that the project was saved, select `Maven` and click `Finish`.

Click `Open` on the welcome screen and navigate to the directory that the project was saved and select `Open`. 
Select `View` in the menu bar and navigate to `Tool Windows` and click `Project` to show up the `Project Tool Window` at top left side. Expand the `guide-{projectid}` project.

The `start` directory contains the starting project that you will build upon.

The `finish` directory contains the finished project that you will build.

At the lower right of the IDE, click `Terminal` to open the console if needed. By default, it should start
in the `guide-{projectid}` directory.

== Configure the build project

From the menu bar, select `Run` and click `Edit Configurations`. 

Click the `+` button at the upper left in the `Run/Debug Configurations` pop up window. 
Select `Maven` under `Add new configuration`.
In the `Name` field, put `Run finish`. In the `Command line` field, put `liberty:run`.
For the `Working directory` field, select the path or navigate to the `finish` directory. 

Fill out the `Name`, `Working directory` and `Command Line` field in order from top to bottom.

Next, click the `+` button at the upper left in the `Run/Debug Configurations` pop up window. 
Select `Maven` under `Add new configuration`. 
In the `Name` field, put `Stop finish`. In the `Command line` field, put `liberty:stop`.
For the `Working directory` field, select the path or navigate to the `finish` directory. 

Once again, click the `+` button at the upper left in the `Run/Debug Configurations` pop up window. 
Select `Maven` under `Add new configuration`.
In the `Name` field, put `Develop start`. In the `Command line` field, put `liberty:dev`.
For the `Working directory` field, select the path or navigate to the `start` directory. 

Finally, click the `+` button at the upper left in the `Run/Debug Configurations` pop up window. 
Select `Maven` under `Add new configuration`. 
In the `Name` field, put `Stop start`. In the `Command line` field, put `liberty:stop`.
For the `Working directory` field, select the path or navigate to the `start` directory. 

You can also use the icons on the toolbar to toggle quickly between the different configurations that were set up
previously.

For both `start` and `finish` project, you are supposed to configure the SDK.

From the menu bar, select `File` and click `Project Structure`. On the panel on the left, locate the `Project Settings` section and select `Project`.

In the `Project SDK` section, click `New`, choose `JDK` and specify the path to the it.

Click `OK` to save changes.

== Try what you'll build

The `finish` directory in the root of this guide contains the finished application. Give it a try before you proceed.

To try out the application, you can select `Run` in the menu bar and click `Run...`. Select `Run finish`
in the pop up window and deploy it to Open Liberty.

The tool window will be activated by default displaying a console which allows you to follow the progress of the build.

Try look at the console out for the `Run finish`. If the following statement `"CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 6.228 seconds."` shows in the console, check out the service at the
http://localhost:9080/LibertyProject/System/properties[^] URL.

You are expected to see the system properties with the format of JSON Strings.

To stop the application, select `Run` in the menu bar and click `Run...` and then select `Stop finish` in the pop up window.

== Developing the microserivce

Select `Run` in the menu bar and click `Run...`. Select `Develop start` in the pop up window which will start the
Open Liberty server in development mode and will listen for file changes.

Check out the service at the
http://localhost:9080/LibertyProject/System/properties[^] URL.

You are expected to see `Context Root Not Found`.

== Configuring the server

Select `View` in the menu bar and navigate to `Tool Windows` and click `Project` to show up the `Project Tool Window` at top left side. Expand the `guide-{projectid}` project and navigate to the `start` directory to begin.

To get the service running, the Open Liberty server needs to be correctly configured.

[role="code_command hotspot", subs="quotes"]
----
#Replace the server configuration file.#
`src/main/liberty/config/server.xml`
----

server.xml
[source,xml,linenums,role="code_column"]
----
include::finish/src/main/liberty/config/server.xml[]
----

The Open Liberty server was started in development mode at the beginning of the guide and all the
changes were automatically picked up.

Check out the service at the
http://localhost:9080/LibertyProject/System/properties[^] URL.

You are expected to see the system properties with the format of JSON Strings.

== Debugging the microservice

You may want to debug the program. After you run `Develop start` you can attach the IntelliJ debugger to the Open Liberty
process.

From the menu bar, select `Run` and click `Edit Configurations`. Click the `+` button at the upper left in the
`Run/Debug Configurations` pop up window. Select `Remote` in `Add new configuration`. Type `7777` into
the `Port` field and `Check` in the `Name` field. Click `OK` to save the changes. Select `Run` from the menu bar and click `Debug...`. Select `Check` in the pop-up window to start the debugger.

In the editor open the class `PropertiesResource` which is located in the `start/src/main/java/io/openliberty/guides/rest` directory. 
Click in the margin on line `34`, which is `return System.getProperties();`. This action will set a breakpoint on that line.

Now refresh the browser at the http://localhost:9080/LibertyProject/System/properties[^] URL. The server will stop at
the breakpoint you set and you can examine the state of your JVM. Select `Run` in the menu bar and click `Resume Program` to continue testing your
application.

== Testing the microservice

You can test this service manually by starting a server and pointing a web browser at the
http://localhost:9080/LibertyProject/System/properties[^] URL. Automated tests are a much better
approach because they trigger a failure if a change introduces a bug. JUnit and the JAX-RS Client
API provide a simple environment to test the application.

You can write tests for the individual units of code outside of a running application server, or they
can be written to call the application server directly. In this example, you will create a test that
does the latter.

EndpointIT.java
[source, Java, linenums, role="code_column hide_tags=comment"]
----
include::finish/src/test/java/it/io/openliberty/guides/rest/EndpointIT.java[]
----

This test class has more lines of code than the resource implementation. This situation is common.
The test method is indicated with the [hotspot=test file=0]`@Test` annotation.

=== Running the tests

Since you started Open Liberty in development mode at the start of the guide, press
`enter/return` key to run the tests. You will see the following output:

[source,role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.rest.EndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.884 sec - in it.io.openliberty.guides.rest.EndpointIT

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

To see whether the tests detect a failure, add an assertion that you know fails, or change the existing
assertion to a constant value that doesn't match the `os.name` system property.

When you are done checking out the service, exit development mode by selecting `Run` in the menu bar and clicking
`Run...` and then selecting `Stop start` in the pop up window. Alternatively, type `q` in the shell session where
you ran the server and then press the `enter/return` key.

== Great work! You're done!

You developed a REST service in Open Liberty using IntelliJ.

== Related Links

Learn more about MicroProfile.

https://microprofile.io/[See the MicroProfile specs^]

https://openliberty.io/docs/ref/microprofile[View the MicroProfile API^]


include::{common-includes}/attribution.adoc[subs="attributes"]
